# Generated by Django 2.2.6 on 2020-01-14 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 1, 14, 15, 8, 51, 461659, tzinfo=utc), verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(default='login', max_length=30, verbose_name='login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(default='surname', max_length=30, verbose_name='surname'),
        ),
    ]
