# Generated by Django 2.2.6 on 2020-01-14 15:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0002_auto_20200114_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 1, 14, 15, 10, 40, 237459, tzinfo=utc), verbose_name='date of birth'),
        ),
    ]
